apiVersion: v1
kind: ConfigMap
metadata:
  name: metric-producer-config
  namespace: default
data:
  # 클러스터 내부 FQDN 사용
  KAFKA_BROKER: "kafka.kafka.svc.cluster.local:9092"
  
  # Node Exporter 메트릭은 일반적으로 Prometheus가 직접 수집
  EXPORTER_URL_NODE: "http://kube-prometheus-stack-prometheus-node-exporter.monitoring.svc.cluster.local:9100/metrics"
  EXPORTER_URL_SPRING: "http://wwwm-spring-be-service.default.svc.cluster.local:8080/actuator/prometheus"
  EXPORTER_URL_MYSQL: "http://wwwm-mysql-exporter-svc.default.svc.cluster.local:9104/metrics"